import 'package:mtag_user_app/core/network/api_client.dart';

/// What the server says about push for this deployment and this user.
class PushStatus {
  const PushStatus({required this.serverCanSend, required this.deviceCount});

  /// `push_available` from the server: whether FCM credentials are configured on the
  /// BACKEND. Distinct from whether this device holds a token — a deployment with no
  /// service-account file cannot send to a perfectly valid token, and an app that reports
  /// "notifications on" against such a server is lying.
  final bool serverCanSend;

  final int deviceCount;
}

/// `/notifications/…` — device registration only.
///
/// There is no "fetch my notifications" call because there is no notification INBOX on the
/// server: alerts are fire-and-forget pushes generated by `post_save` signals on
/// Transaction and TopupRequest. So the app must never render a notification history — it
/// would be empty on a fresh install and after every reinstall, which reads as lost money
/// rather than as absent history.
class PushRepository {
  PushRepository({required ApiClient client}) : _client = client;

  final ApiClient _client;

  /// Registers a token against the CURRENT session.
  ///
  /// The server keys on the token and reassigns it to whoever registers it, which is what
  /// makes a handed-on phone stop delivering the previous owner's balances.
  Future<PushStatus> register({
    required String token,
    required String platform,
  }) async {
    final result = await _client.post<PushStatus>(
      'notifications/devices/register/',
      body: {'token': token, 'platform': platform},
      parse: (data) {
        final map = data is Map<String, dynamic> ? data : const <String, dynamic>{};
        return PushStatus(
          serverCanSend: map['push_available'] == true,
          deviceCount: 1,
        );
      },
    );
    return result ?? const PushStatus(serverCanSend: false, deviceCount: 0);
  }

  /// Called on sign-out, BEFORE the cookies are cleared.
  ///
  /// Ordering matters: the endpoint is `IsAuthenticated` and scopes the delete to
  /// `user=request.user`, so calling it after the session is gone returns 401 and leaves
  /// the row in place — meaning the next person to hold the phone keeps receiving the
  /// previous user's balance notifications.
  Future<void> unregister({required String token}) async {
    await _client.post<void>(
      'notifications/devices/unregister/',
      body: {'token': token},
    );
  }

  Future<PushStatus> status() => _client.get<PushStatus>(
    'notifications/status/',
    parse: (data) {
      final map = data is Map<String, dynamic> ? data : const <String, dynamic>{};
      final devices = map['devices'];
      return PushStatus(
        serverCanSend: map['push_available'] == true,
        deviceCount: devices is List ? devices.length : 0,
      );
    },
  );
}
