-- ============================================================================
-- RETIRED — DO NOT RESTORE FROM THIS FILE.
--
-- This dump is stale. Verified missing tables:
--     daily_summaries, scan_buffer, unregistered_inventory,
--     booth_inventory_assignment, tag_activation,
--     vehicle_categories, fare_matrix
-- (sync_log, plazas.plaza_id and tags.tid ARE present — but seven missing
-- tables is more than enough to leave a database unusable.)
-- It also contains NO django_migrations rows, so a database restored from it
-- looks "empty" to Django: `migrate` then fails with "relation already exists"
-- and needs --fake-initial to recover. That is exactly how the test database on
-- 192.168.78.198 ended up unusable.
--
-- The schema comes from migrations, and only from migrations:
--     python manage.py migrate
--
-- Kept for historical reference only. The guard below aborts execution.
-- To regenerate a current reference dump from a migrated database:
--     pg_dump --schema-only --no-owner master_tag_db > sql/schema.sql
--     (then delete this guard block)
-- ============================================================================
DO $$
BEGIN
    RAISE EXCEPTION
        'sql/schema.sql is retired and incomplete. Use: python manage.py migrate';
END
$$;

--
-- PostgreSQL database dump
--

-- Dumped from database version 16rc1
-- Dumped by pg_dump version 16rc1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id uuid NOT NULL,
    balance numeric(12,2) NOT NULL,
    balance_updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    vehicle_id uuid NOT NULL
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: pending_gate_opens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_gate_opens (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    executed_at timestamp with time zone,
    lane_id uuid,
    plaza_id uuid NOT NULL
);


--
-- Name: pending_gate_opens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pending_gate_opens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pending_gate_opens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plazas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plazas (
    id uuid NOT NULL,
    plaza_id integer NOT NULL,
    name character varying(100) NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    is_active boolean NOT NULL
);


--
-- Name: sync_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_log (
    id bigint NOT NULL,
    table_name character varying(60) NOT NULL,
    last_pull_at timestamp with time zone,
    last_push_at timestamp with time zone
);


--
-- Name: sync_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sync_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sync_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id uuid NOT NULL,
    tag_serial character varying(24) NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    expiry_date date NOT NULL,
    status character varying(20) NOT NULL,
    last_scanned_at timestamp with time zone,
    vehicle_id uuid,
    epc character varying(24) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    tid character varying(24)
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: toll_lanes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.toll_lanes (
    id uuid NOT NULL,
    lane_number integer NOT NULL,
    is_active boolean NOT NULL,
    plaza_id uuid NOT NULL
);


--
-- Name: toll_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.toll_rates (
    id uuid NOT NULL,
    vehicle_type character varying(20) NOT NULL,
    rate numeric(8,2) NOT NULL,
    peak_multiplier numeric(4,2) NOT NULL,
    effective_from date NOT NULL,
    entry_plaza_id uuid NOT NULL,
    exit_plaza_id uuid NOT NULL
);


--
-- Name: toll_trips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.toll_trips (
    id uuid NOT NULL,
    entry_time timestamp with time zone NOT NULL,
    exit_time timestamp with time zone,
    charge_amount numeric(10,2),
    balance_before numeric(12,2),
    balance_after numeric(12,2),
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    account_id uuid NOT NULL,
    entry_lane_id uuid,
    entry_plaza_id uuid NOT NULL,
    exit_lane_id uuid,
    exit_plaza_id uuid,
    tag_id uuid NOT NULL,
    vehicle_id uuid NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: topup_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.topup_requests (
    id uuid NOT NULL,
    jazzcash_txn_id character varying(100),
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    account_id uuid NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id uuid NOT NULL,
    tag_serial character varying(24) NOT NULL,
    transaction_type character varying(30) NOT NULL,
    amount numeric(10,2) NOT NULL,
    balance_before numeric(12,2) NOT NULL,
    balance_after numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL,
    processed_at timestamp with time zone NOT NULL,
    account_id uuid NOT NULL,
    toll_lane_id uuid,
    toll_trip_id uuid,
    reference_id uuid,
    idempotency_key character varying(64),
    source character varying(30)
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    uuid uuid NOT NULL,
    full_name character varying(100) NOT NULL,
    cnic character varying(15),
    phone character varying(20) NOT NULL,
    user_role character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_login_at timestamp with time zone,
    created_by_id bigint
);


--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicles (
    id uuid NOT NULL,
    plate_number character varying(20) NOT NULL,
    vehicle_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_vehicle_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_vehicle_id_key UNIQUE (vehicle_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: pending_gate_opens pending_gate_opens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_gate_opens
    ADD CONSTRAINT pending_gate_opens_pkey PRIMARY KEY (id);


--
-- Name: plazas plazas_plaza_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plazas
    ADD CONSTRAINT plazas_plaza_id_key UNIQUE (plaza_id);


--
-- Name: plazas plazas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plazas
    ADD CONSTRAINT plazas_pkey PRIMARY KEY (id);


--
-- Name: sync_log sync_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_log
    ADD CONSTRAINT sync_log_pkey PRIMARY KEY (id);


--
-- Name: sync_log sync_log_table_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_log
    ADD CONSTRAINT sync_log_table_name_key UNIQUE (table_name);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: tags tags_tag_serial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_tag_serial_key UNIQUE (tag_serial);


--
-- Name: tags tags_tid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_tid_key UNIQUE (tid);


--
-- Name: tags tags_vehicle_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_vehicle_id_key UNIQUE (vehicle_id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: toll_lanes toll_lanes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_lanes
    ADD CONSTRAINT toll_lanes_pkey PRIMARY KEY (id);


--
-- Name: toll_lanes toll_lanes_plaza_id_lane_number_a65b04f0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_lanes
    ADD CONSTRAINT toll_lanes_plaza_id_lane_number_a65b04f0_uniq UNIQUE (plaza_id, lane_number);


--
-- Name: toll_rates toll_rates_entry_plaza_id_exit_plaz_4e0c6368_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_rates
    ADD CONSTRAINT toll_rates_entry_plaza_id_exit_plaz_4e0c6368_uniq UNIQUE (entry_plaza_id, exit_plaza_id, vehicle_type, effective_from);


--
-- Name: toll_rates toll_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_rates
    ADD CONSTRAINT toll_rates_pkey PRIMARY KEY (id);


--
-- Name: toll_trips toll_trips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_pkey PRIMARY KEY (id);


--
-- Name: topup_requests topup_requests_jazzcash_txn_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topup_requests
    ADD CONSTRAINT topup_requests_jazzcash_txn_id_key UNIQUE (jazzcash_txn_id);


--
-- Name: topup_requests topup_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topup_requests
    ADD CONSTRAINT topup_requests_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users users_cnic_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_cnic_key UNIQUE (cnic);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_phone_key UNIQUE (phone);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_uuid_key UNIQUE (uuid);


--
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- Name: vehicles vehicles_plate_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_plate_number_key UNIQUE (plate_number);


--
-- Name: accounts_user_id_7f1e1f1e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_id_7f1e1f1e ON public.accounts USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: pending_gate_opens_created_at_db132515; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pending_gate_opens_created_at_db132515 ON public.pending_gate_opens USING btree (created_at);


--
-- Name: pending_gate_opens_lane_id_66a99042; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pending_gate_opens_lane_id_66a99042 ON public.pending_gate_opens USING btree (lane_id);


--
-- Name: pending_gate_opens_plaza_id_8694ec58; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pending_gate_opens_plaza_id_8694ec58 ON public.pending_gate_opens USING btree (plaza_id);


--
-- Name: sync_log_table_name_5aeaecb7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sync_log_table_name_5aeaecb7_like ON public.sync_log USING btree (table_name varchar_pattern_ops);


--
-- Name: tags_tag_ser_c6cd07_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tags_tag_ser_c6cd07_idx ON public.tags USING btree (tag_serial);


--
-- Name: tags_tag_serial_1359236f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tags_tag_serial_1359236f_like ON public.tags USING btree (tag_serial varchar_pattern_ops);


--
-- Name: tags_tid_e5b83e80_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tags_tid_e5b83e80_like ON public.tags USING btree (tid varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: toll_lanes_plaza_id_521f76c8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_lanes_plaza_id_521f76c8 ON public.toll_lanes USING btree (plaza_id);


--
-- Name: toll_rates_entry_plaza_id_fdca0a4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_rates_entry_plaza_id_fdca0a4b ON public.toll_rates USING btree (entry_plaza_id);


--
-- Name: toll_rates_exit_plaza_id_7e3ed556; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_rates_exit_plaza_id_7e3ed556 ON public.toll_rates USING btree (exit_plaza_id);


--
-- Name: toll_trips_account_id_d2e40118; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_account_id_d2e40118 ON public.toll_trips USING btree (account_id);


--
-- Name: toll_trips_entry_lane_id_3b607e12; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_entry_lane_id_3b607e12 ON public.toll_trips USING btree (entry_lane_id);


--
-- Name: toll_trips_entry_plaza_id_f8aad7f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_entry_plaza_id_f8aad7f8 ON public.toll_trips USING btree (entry_plaza_id);


--
-- Name: toll_trips_entry_t_426506_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_entry_t_426506_idx ON public.toll_trips USING btree (entry_time);


--
-- Name: toll_trips_exit_lane_id_431890d4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_exit_lane_id_431890d4 ON public.toll_trips USING btree (exit_lane_id);


--
-- Name: toll_trips_exit_plaza_id_a281025e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_exit_plaza_id_a281025e ON public.toll_trips USING btree (exit_plaza_id);


--
-- Name: toll_trips_tag_id_8e844f0a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_tag_id_8e844f0a ON public.toll_trips USING btree (tag_id);


--
-- Name: toll_trips_updated_eff782_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_updated_eff782_idx ON public.toll_trips USING btree (updated_at);


--
-- Name: toll_trips_vehicle_146bc0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_vehicle_146bc0_idx ON public.toll_trips USING btree (vehicle_id, status);


--
-- Name: toll_trips_vehicle_id_59f13be8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX toll_trips_vehicle_id_59f13be8 ON public.toll_trips USING btree (vehicle_id);


--
-- Name: topup_requests_account_id_4d7a980d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX topup_requests_account_id_4d7a980d ON public.topup_requests USING btree (account_id);


--
-- Name: topup_requests_jazzcash_txn_id_677a855a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX topup_requests_jazzcash_txn_id_677a855a_like ON public.topup_requests USING btree (jazzcash_txn_id varchar_pattern_ops);


--
-- Name: topup_requests_user_id_1c8dec3d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX topup_requests_user_id_1c8dec3d ON public.topup_requests USING btree (user_id);


--
-- Name: transaction_process_874789_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transaction_process_874789_idx ON public.transactions USING btree (processed_at);


--
-- Name: transactions_account_id_d92b47af; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_account_id_d92b47af ON public.transactions USING btree (account_id);


--
-- Name: transactions_idempotency_key_47231c55_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_idempotency_key_47231c55_like ON public.transactions USING btree (idempotency_key varchar_pattern_ops);


--
-- Name: transactions_processed_at_5dc1f644; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_processed_at_5dc1f644 ON public.transactions USING btree (processed_at);


--
-- Name: transactions_reference_id_5e1da98a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_reference_id_5e1da98a ON public.transactions USING btree (reference_id);


--
-- Name: transactions_toll_lane_id_68551288; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_toll_lane_id_68551288 ON public.transactions USING btree (toll_lane_id);


--
-- Name: transactions_toll_trip_id_fa9956bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transactions_toll_trip_id_fa9956bf ON public.transactions USING btree (toll_trip_id);


--
-- Name: unique_active_trip_per_vehicle; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_active_trip_per_vehicle ON public.toll_trips USING btree (vehicle_id) WHERE ((status)::text = 'active'::text);


--
-- Name: users_cnic_37877b95_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_cnic_37877b95_like ON public.users USING btree (cnic varchar_pattern_ops);


--
-- Name: users_cnic_6d5b4b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_cnic_6d5b4b_idx ON public.users USING btree (cnic);


--
-- Name: users_created_by_id_19a92469; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_created_by_id_19a92469 ON public.users USING btree (created_by_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_phone_2b77170a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_phone_2b77170a_like ON public.users USING btree (phone varchar_pattern_ops);


--
-- Name: users_phone_af6883_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_phone_af6883_idx ON public.users USING btree (phone);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: vehicles_owner_id_8cbe0576; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_owner_id_8cbe0576 ON public.vehicles USING btree (owner_id);


--
-- Name: vehicles_plate_n_de64b1_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_plate_n_de64b1_idx ON public.vehicles USING btree (plate_number);


--
-- Name: vehicles_plate_number_5dc3e111_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vehicles_plate_number_5dc3e111_like ON public.vehicles USING btree (plate_number varchar_pattern_ops);


--
-- Name: accounts accounts_user_id_7f1e1f1e_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_user_id_7f1e1f1e_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts accounts_vehicle_id_ac881383_fk_vehicles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_vehicle_id_ac881383_fk_vehicles_id FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pending_gate_opens pending_gate_opens_lane_id_66a99042_fk_toll_lanes_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_gate_opens
    ADD CONSTRAINT pending_gate_opens_lane_id_66a99042_fk_toll_lanes_id FOREIGN KEY (lane_id) REFERENCES public.toll_lanes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pending_gate_opens pending_gate_opens_plaza_id_8694ec58_fk_plazas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_gate_opens
    ADD CONSTRAINT pending_gate_opens_plaza_id_8694ec58_fk_plazas_id FOREIGN KEY (plaza_id) REFERENCES public.plazas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tags tags_vehicle_id_2ac2c4e0_fk_vehicles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_vehicle_id_2ac2c4e0_fk_vehicles_id FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_lanes toll_lanes_plaza_id_521f76c8_fk_plazas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_lanes
    ADD CONSTRAINT toll_lanes_plaza_id_521f76c8_fk_plazas_id FOREIGN KEY (plaza_id) REFERENCES public.plazas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_rates toll_rates_entry_plaza_id_fdca0a4b_fk_plazas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_rates
    ADD CONSTRAINT toll_rates_entry_plaza_id_fdca0a4b_fk_plazas_id FOREIGN KEY (entry_plaza_id) REFERENCES public.plazas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_rates toll_rates_exit_plaza_id_7e3ed556_fk_plazas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_rates
    ADD CONSTRAINT toll_rates_exit_plaza_id_7e3ed556_fk_plazas_id FOREIGN KEY (exit_plaza_id) REFERENCES public.plazas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_account_id_d2e40118_fk_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_account_id_d2e40118_fk_accounts_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_entry_lane_id_3b607e12_fk_toll_lanes_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_entry_lane_id_3b607e12_fk_toll_lanes_id FOREIGN KEY (entry_lane_id) REFERENCES public.toll_lanes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_entry_plaza_id_f8aad7f8_fk_plazas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_entry_plaza_id_f8aad7f8_fk_plazas_id FOREIGN KEY (entry_plaza_id) REFERENCES public.plazas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_exit_lane_id_431890d4_fk_toll_lanes_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_exit_lane_id_431890d4_fk_toll_lanes_id FOREIGN KEY (exit_lane_id) REFERENCES public.toll_lanes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_exit_plaza_id_a281025e_fk_plazas_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_exit_plaza_id_a281025e_fk_plazas_id FOREIGN KEY (exit_plaza_id) REFERENCES public.plazas(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_tag_id_8e844f0a_fk_tags_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_tag_id_8e844f0a_fk_tags_id FOREIGN KEY (tag_id) REFERENCES public.tags(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: toll_trips toll_trips_vehicle_id_59f13be8_fk_vehicles_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.toll_trips
    ADD CONSTRAINT toll_trips_vehicle_id_59f13be8_fk_vehicles_id FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: topup_requests topup_requests_account_id_4d7a980d_fk_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topup_requests
    ADD CONSTRAINT topup_requests_account_id_4d7a980d_fk_accounts_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: topup_requests topup_requests_user_id_1c8dec3d_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.topup_requests
    ADD CONSTRAINT topup_requests_user_id_1c8dec3d_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions transactions_account_id_d92b47af_fk_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_account_id_d92b47af_fk_accounts_id FOREIGN KEY (account_id) REFERENCES public.accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions transactions_toll_lane_id_68551288_fk_toll_lanes_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_toll_lane_id_68551288_fk_toll_lanes_id FOREIGN KEY (toll_lane_id) REFERENCES public.toll_lanes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions transactions_toll_trip_id_fa9956bf_fk_toll_trips_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_toll_trip_id_fa9956bf_fk_toll_trips_id FOREIGN KEY (toll_trip_id) REFERENCES public.toll_trips(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_created_by_id_19a92469_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_created_by_id_19a92469_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicles vehicles_owner_id_8cbe0576_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_owner_id_8cbe0576_fk_users_id FOREIGN KEY (owner_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

