# Generated by Django 6.0.4 on 2026-08-09 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_serial', models.CharField(max_length=24, unique=True)),
                ('tid', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('epc', models.CharField(blank=True, default='', max_length=24)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_index', models.IntegerField(help_text='Stable numeric key referenced by fare_matrix.category_index', unique=True)),
                ('code', models.CharField(help_text="Matches Vehicle.vehicle_type, e.g. 'car', 'truck_2axle'", max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'vehicle categories',
                'db_table': 'vehicle_categories',
                'ordering': ['category_index'],
            },
        ),
        migrations.CreateModel(
            name='UnregisteredInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_serial', models.CharField(max_length=50, unique=True)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('epc', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car / Jeep / Taxi / Pickup'), ('wagon', 'Wagon / Hiace'), ('coach', 'Coach / Coaster / Mini Bus'), ('large_bus', 'Large Bus'), ('truck_2axle', '2 Axle Truck'), ('truck_3axle', '3 Axle Truck'), ('truck_4axle', '4 or More Axle Truck'), ('motorcycle', 'Motorcycle')], default='car', max_length=20)),
                ('vehicle_color', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('booth_assigned', 'Booth Assigned'), ('activated', 'Activated')], default='unregistered', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('booth_assigned_id', models.IntegerField(blank=True, null=True)),
                ('booth_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_activated_booth_id', models.IntegerField(blank=True, null=True)),
                ('first_activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_for_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_from_inventory', to='accounts.account')),
            ],
            options={
                'db_table': 'unregistered_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoothInventoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_id', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_assignments', to='vehicles.unregisteredinventory')),
            ],
            options={
                'db_table': 'booth_inventory_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car / Jeep / Taxi / Pickup'), ('wagon', 'Wagon / Hiace'), ('coach', 'Coach / Coaster / Mini Bus'), ('large_bus', 'Large Bus'), ('truck_2axle', '2 Axle Truck'), ('truck_3axle', '3 Axle Truck'), ('truck_4axle', '4 or More Axle Truck'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_serial', models.CharField(db_index=True, max_length=24)),
                ('plate_number', models.CharField(blank=True, default='', max_length=20)),
                ('assigned_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='vehicles.tag')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_assignments', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'tag_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='vehicles.vehicle'),
        ),
        migrations.CreateModel(
            name='ScanBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=24)),
                ('epc', models.CharField(blank=True, default='', max_length=24)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_buffer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_buffer',
                'ordering': ['-scanned_at'],
                'unique_together': {('user', 'tid')},
            },
        ),
        migrations.CreateModel(
            name='TagActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_serial', models.CharField(max_length=50, unique=True)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('first_scan_booth_id', models.IntegerField()),
                ('first_scan_at', models.DateTimeField()),
                ('activation_type', models.CharField(choices=[('auto_created', 'Auto Created'), ('linked', 'Linked to Existing')], default='auto_created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_activations', to='accounts.account')),
            ],
            options={
                'db_table': 'tag_activations',
                'ordering': ['-first_scan_at'],
                'indexes': [models.Index(fields=['tag_serial'], name='tag_activat_tag_ser_f66f68_idx'), models.Index(fields=['tid'], name='tag_activat_tid_9e0986_idx'), models.Index(fields=['first_scan_booth_id'], name='tag_activat_first_s_67dea0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['tag_serial'], name='unregistere_tag_ser_03c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['tid'], name='unregistere_tid_cd7838_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['status'], name='unregistere_status_c7fd51_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['booth_assigned_id'], name='unregistere_booth_a_81875e_idx'),
        ),
        migrations.AddIndex(
            model_name='boothinventoryassignment',
            index=models.Index(fields=['booth_id'], name='booth_inven_booth_i_44701f_idx'),
        ),
        migrations.AddIndex(
            model_name='boothinventoryassignment',
            index=models.Index(fields=['is_active'], name='booth_inven_is_acti_2ee9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='vehicles_plate_n_de64b1_idx'),
        ),
        migrations.AddIndex(
            model_name='tagassignment',
            index=models.Index(fields=['tag_serial', '-assigned_at'], name='tag_assignm_tag_ser_489ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='tagassignment',
            index=models.Index(fields=['vehicle', '-assigned_at'], name='tag_assignm_vehicle_7525de_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('tag_serial',), name='unique_open_assignment_per_tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_serial'], name='tags_tag_ser_c6cd07_idx'),
        ),
    ]
