# Generated by Django 6.0.4 on 2026-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
    ]
