# Generated by Django 6.0.4 on 2026-08-19 14:37

import apps.vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='expiry_date',
            field=models.DateField(default=apps.vehicles.models.default_tag_expiry),
        ),
    ]
