# Generated by Django 6.0.4 on 2026-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_tag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='epc',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
