# Generated by Django 6.0.4 on 2026-05-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_add_epc_to_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='vehicles.vehicle'),
        ),
    ]
