# Generated by Django 6.0.4 on 2026-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_tag_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tid',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
