# Generated by Django 6.0.4 on 2026-06-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_tag_tid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=24)),
                ('epc', models.CharField(blank=True, default='', max_length=24)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_buffer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_buffer',
                'ordering': ['-scanned_at'],
                'unique_together': {('user', 'tid')},
            },
        ),
    ]
