# Generated by Django 6.0.4 on 2026-07-10 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_idempotency'),
        ('vehicles', '0007_scanbuffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_serial', models.CharField(max_length=50, unique=True)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('epc', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('bus', 'Bus')], default='car', max_length=20)),
                ('vehicle_color', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('booth_assigned', 'Booth Assigned'), ('activated', 'Activated')], default='unregistered', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('booth_assigned_id', models.IntegerField(blank=True, null=True)),
                ('booth_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_activated_booth_id', models.IntegerField(blank=True, null=True)),
                ('first_activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_for_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_from_inventory', to='accounts.account')),
            ],
            options={
                'db_table': 'unregistered_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoothInventoryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booth_id', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_assignments', to='vehicles.unregisteredinventory')),
            ],
            options={
                'db_table': 'booth_inventory_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TagActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_serial', models.CharField(max_length=50, unique=True)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('first_scan_booth_id', models.IntegerField()),
                ('first_scan_at', models.DateTimeField()),
                ('activation_type', models.CharField(choices=[('auto_created', 'Auto Created'), ('linked', 'Linked to Existing')], default='auto_created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_activations', to='accounts.account')),
            ],
            options={
                'db_table': 'tag_activations',
                'ordering': ['-first_scan_at'],
                'indexes': [models.Index(fields=['tag_serial'], name='tag_activat_tag_ser_f66f68_idx'), models.Index(fields=['tid'], name='tag_activat_tid_9e0986_idx'), models.Index(fields=['first_scan_booth_id'], name='tag_activat_first_s_67dea0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['tag_serial'], name='unregistere_tag_ser_03c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['tid'], name='unregistere_tid_cd7838_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['status'], name='unregistere_status_c7fd51_idx'),
        ),
        migrations.AddIndex(
            model_name='unregisteredinventory',
            index=models.Index(fields=['booth_assigned_id'], name='unregistere_booth_a_81875e_idx'),
        ),
        migrations.AddIndex(
            model_name='boothinventoryassignment',
            index=models.Index(fields=['booth_id'], name='booth_inven_booth_i_44701f_idx'),
        ),
        migrations.AddIndex(
            model_name='boothinventoryassignment',
            index=models.Index(fields=['is_active'], name='booth_inven_is_acti_2ee9ed_idx'),
        ),
    ]
