# Generated by Django 6.0.4 on 2026-08-08 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehiclecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_serial', models.CharField(db_index=True, max_length=24)),
                ('plate_number', models.CharField(blank=True, default='', max_length=20)),
                ('assigned_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='vehicles.tag')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_assignments', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'tag_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['tag_serial', '-assigned_at'], name='tag_assignm_tag_ser_489ffe_idx'), models.Index(fields=['vehicle', '-assigned_at'], name='tag_assignm_vehicle_7525de_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('tag_serial',), name='unique_open_assignment_per_tag')],
            },
        ),
    ]
