# Generated by Django 6.0.4 on 2026-04-28 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plazas',
            },
        ),
        migrations.CreateModel(
            name='TollLane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lane_number', models.IntegerField()),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('both', 'Both')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='tolls.plaza')),
            ],
            options={
                'db_table': 'toll_lanes',
            },
        ),
        migrations.CreateModel(
            name='TollRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('bus', 'Bus')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peak_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('effective_from', models.DateField()),
                ('entry_plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_rates', to='tolls.plaza')),
                ('exit_plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_rates', to='tolls.plaza')),
            ],
            options={
                'db_table': 'toll_rates',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TollTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounts.account')),
                ('entry_lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_trips', to='tolls.tolllane')),
                ('entry_plaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_trips', to='tolls.plaza')),
                ('exit_lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_trips', to='tolls.tolllane')),
                ('exit_plaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_trips', to='tolls.plaza')),
            ],
            options={
                'db_table': 'toll_trips',
            },
        ),
    ]
