# Generated by Django 6.0.4 on 2026-04-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tolls', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolltrip',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.tag'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='tolllane',
            unique_together={('plaza', 'lane_number')},
        ),
        migrations.AlterUniqueTogether(
            name='tollrate',
            unique_together={('entry_plaza', 'exit_plaza', 'vehicle_type', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['vehicle', 'status'], name='toll_trips_vehicle_146bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['entry_time'], name='toll_trips_entry_t_426506_idx'),
        ),
    ]
