# Generated by Django 6.0.4 on 2026-08-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('tolls', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farematrix',
            name='category',
            field=models.ForeignKey(db_column='category_index', on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='vehicles.vehiclecategory', to_field='category_index'),
        ),
        migrations.AddField(
            model_name='pendinggateopen',
            name='plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_opens', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='from_plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares_from', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='to_plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares_to', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='tolllane',
            name='plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='pendinggateopen',
            name='lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tolls.tolllane'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='tolls.tolllane'),
        ),
        migrations.AddField(
            model_name='tollrate',
            name='entry_plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_rates', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='tollrate',
            name='exit_plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_rates', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='entry_lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_trips', to='tolls.tolllane'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='entry_plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_trips', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='exit_lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_trips', to='tolls.tolllane'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='exit_plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_trips', to='tolls.plaza'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.tag'),
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='farematrix',
            index=models.Index(fields=['from_plaza', 'to_plaza', 'category'], name='idx_fare_from_to_cat'),
        ),
        migrations.AlterUniqueTogether(
            name='farematrix',
            unique_together={('from_plaza', 'to_plaza', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='tolllane',
            unique_together={('plaza', 'lane_number')},
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['date', 'plaza'], name='daily_summa_date_b87549_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('date', 'plaza', 'lane', 'vehicle_type')},
        ),
        migrations.AlterUniqueTogether(
            name='tollrate',
            unique_together={('entry_plaza', 'exit_plaza', 'vehicle_type', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['vehicle', 'status'], name='toll_trips_vehicle_146bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['entry_time'], name='toll_trips_entry_t_426506_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['updated_at'], name='toll_trips_updated_eff782_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['entry_plaza', 'entry_time'], name='toll_trips_entry_p_0a2bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(condition=models.Q(('status', 'completed')), fields=['exit_plaza', 'exit_time'], name='idx_trips_exit_plaza_time'),
        ),
        migrations.AddConstraint(
            model_name='tolltrip',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vehicle',), name='unique_active_trip_per_vehicle'),
        ),
    ]
