# Generated by Django 6.0.4 on 2026-04-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolllane',
            name='direction',
        ),
    ]
