# Generated by Django 6.0.4 on 2026-08-29 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Booth LAN IP or hostname', max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_user', models.CharField(blank=True, default='', max_length=64)),
                ('reported_version', models.CharField(blank=True, default='', max_length=64)),
                ('pm2_summary', models.TextField(blank=True, default='')),
                ('reachable', models.BooleanField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='tolls.tolllane')),
            ],
            options={
                'db_table': 'booth_machines',
                'ordering': ['lane__plaza__plaza_id', 'lane__lane_number'],
            },
        ),
        migrations.CreateModel(
            name='BoothDeployJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check', 'Check version'), ('update', 'Update code')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('from_version', models.CharField(blank=True, default='', max_length=64)),
                ('to_version', models.CharField(blank=True, default='', max_length=64)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('log', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth_jobs', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tolls.boothmachine')),
            ],
            options={
                'db_table': 'booth_deploy_jobs',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='booth_deplo_status_bddd6f_idx')],
            },
        ),
    ]
