# Generated by Django 6.0.4 on 2026-04-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0003_remove_lane_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingGateOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tolls.tolllane')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_opens', to='tolls.plaza')),
            ],
            options={
                'db_table': 'pending_gate_opens',
            },
        ),
    ]
