# Generated by Django 6.0.4 on 2026-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_idempotency'),
        ('tolls', '0005_tolltrip_unique_active_constraint'),
        ('vehicles', '0004_tag_vehicle_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=60, unique=True)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_log',
            },
        ),
        migrations.AddField(
            model_name='tolltrip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['updated_at'], name='toll_trips_updated_eff782_idx'),
        ),
    ]
