# Generated by Django 6.0.4 on 2026-08-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_idempotency'),
        ('tolls', '0009_farematrix'),
        ('vehicles', '0010_vehiclecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('entries', models.IntegerField(default=0)),
                ('exits', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'daily_summaries',
            },
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(fields=['entry_plaza', 'entry_time'], name='toll_trips_entry_p_0a2bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='tolltrip',
            index=models.Index(condition=models.Q(('status', 'completed')), fields=['exit_plaza', 'exit_time'], name='idx_trips_exit_plaza_time'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='tolls.tolllane'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='plaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='tolls.plaza'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['date', 'plaza'], name='daily_summa_date_b87549_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('date', 'plaza', 'lane', 'vehicle_type')},
        ),
    ]
