# Generated by Django 6.0.4 on 2026-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('toll_deduction', 'Toll Deduction'), ('topup', 'Top-up'), ('refund', 'Refund'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=30),
        ),
    ]
