"""Capture real API responses as JSON fixtures for the M-Tag User App's tests.

The Flutter models are hand-written parsers pinned to these serializers. A test that
feeds them fixtures someone typed by hand only proves the parser matches the fixture — so
these are generated by driving the ACTUAL views through DRF, against a real database, with
a real consumer account. If a serializer gains, loses or renames a field, regenerating
these makes the Flutter tests fail, which is the point.

    python manage.py dump_api_fixtures --out ../mtag_user_app/test/fixtures

Uses a transaction that is rolled back, so it never leaves rows behind.
"""

import json
import os
from datetime import date
from decimal import Decimal
from pathlib import Path

from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils import timezone
from rest_framework.test import APIClient

from apps.accounts.models import (
    Account, Transaction, TransactionSource, TransactionStatus, TransactionType,
)
from apps.payments.models import TopupRequest, TopupStatus
from apps.tolls.models import FareMatrix, Plaza, TollTrip, TripStatus
from apps.users.models import User
from apps.vehicles.models import Tag, TagStatus, Vehicle, VehicleCategory


class Command(BaseCommand):
    help = "Dump real API responses as fixtures for the Flutter app's contract tests."

    def add_arguments(self, parser):
        parser.add_argument(
            '--out',
            default='../mtag_user_app/test/fixtures',
            help='Directory to write the JSON fixtures into.',
        )

    def handle(self, *args, **options):
        out_dir = Path(options['out']).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)

        # Everything happens inside a transaction that is rolled back at the end, so this
        # is safe to run against a populated dev database.
        try:
            with transaction.atomic():
                fixtures = self._capture()
                for name, payload in fixtures.items():
                    path = out_dir / f'{name}.json'
                    path.write_text(
                        json.dumps(payload, indent=2, ensure_ascii=False) + '\n'
                    )
                    self.stdout.write(f'wrote {path.name}')
                raise _Rollback
        except _Rollback:
            self.stdout.write(self.style.SUCCESS(
                f'{len(fixtures)} fixtures written to {out_dir} (database rolled back)'
            ))

    def _capture(self):
        suffix = timezone.now().strftime('%H%M%S%f')

        owner = User.objects.create_user(
            phone=f'0300{suffix[:7]}',
            password='fixturepass123',
            full_name='Fixture Holder',
            cnic='42101-1234567-1',
        )

        entry = Plaza.objects.create(
            plaza_id=9001, name='Fixture Main Toll Plaza',
            latitude=Decimal('24.850000'), longitude=Decimal('67.100000'),
        )
        exit_plaza = Plaza.objects.create(plaza_id=9101, name='Fixture Interchange')

        car = VehicleCategory.objects.create(
            category_index=901, code='car', name='Car / Jeep / Taxi / Pickup',
        )
        truck = VehicleCategory.objects.create(
            category_index=905, code='truck_2axle', name='2 Axle Truck',
        )
        # Deliberately asymmetric, so the fixture proves the app cannot assume symmetry.
        FareMatrix.objects.create(
            from_plaza=entry, to_plaza=exit_plaza, category=car, fare=Decimal('100.00'),
        )
        FareMatrix.objects.create(
            from_plaza=exit_plaza, to_plaza=entry, category=car, fare=Decimal('120.00'),
        )
        FareMatrix.objects.create(
            from_plaza=entry, to_plaza=exit_plaza, category=truck, fare=Decimal('350.00'),
        )

        # Vehicle 1: tag fitted, healthy balance.
        vehicle = Vehicle.objects.create(
            owner=owner, plate_number=f'FIX{suffix[:4]}', vehicle_type='car',
        )
        account = Account.objects.create(
            vehicle=vehicle, user=owner, balance=Decimal('1250.00'),
        )
        tag = Tag.objects.create(
            tag_serial=f'SER{suffix}', tid=f'E280117{suffix}', epc=f'EPC{suffix}',
            vehicle=vehicle, expiry_date=date(2099, 12, 31), status=TagStatus.ACTIVE,
            last_scanned_at=timezone.now(),
        )

        # Vehicle 2: NO tag and a blocked-level balance — the two states the app has to
        # render specially, and the ones a happy-path fixture would miss.
        bare = Vehicle.objects.create(
            owner=owner, plate_number=f'BAR{suffix[:4]}', vehicle_type='truck_2axle',
        )
        Account.objects.create(vehicle=bare, user=owner, balance=Decimal('42.00'))

        # A toll taken at an OFFLINE booth, which is what the "synced from booth" note
        # keys on.
        Transaction.objects.create(
            account=account, tag_serial=tag.tag_serial,
            transaction_type=TransactionType.TOLL_DEDUCTION, amount=Decimal('120.00'),
            balance_before=Decimal('1370.00'), balance_after=Decimal('1250.00'),
            status=TransactionStatus.SUCCESS,
            source=TransactionSource.OFFLINE_EXIT_SYNC,
        )
        Transaction.objects.create(
            account=account, tag_serial=tag.tag_serial,
            transaction_type=TransactionType.TOPUP, amount=Decimal('1000.00'),
            balance_before=Decimal('370.00'), balance_after=Decimal('1370.00'),
            status=TransactionStatus.SUCCESS,
            source=TransactionSource.TOPUP_JAZZCASH,
        )
        # A transaction with source NULL — several server paths create these, so the app
        # must not assume the field is populated.
        Transaction.objects.create(
            account=account, transaction_type=TransactionType.REFUND,
            amount=Decimal('60.00'),
            balance_before=Decimal('310.00'), balance_after=Decimal('370.00'),
            status=TransactionStatus.SUCCESS,
        )

        TopupRequest.objects.create(
            account=account, user=owner, amount=Decimal('500.00'),
            status=TopupStatus.PENDING,
        )

        # A completed trip and an ACTIVE one (entered, not yet exited) — the active trip
        # has null exit/charge fields, which is a valid state and not missing data.
        TollTrip.objects.create(
            vehicle=vehicle, tag=tag, account=account,
            entry_plaza=entry, exit_plaza=exit_plaza, exit_time=timezone.now(),
            charge_amount=Decimal('120.00'),
            balance_before=Decimal('1370.00'), balance_after=Decimal('1250.00'),
            status=TripStatus.COMPLETED,
        )
        TollTrip.objects.create(
            vehicle=bare, tag=tag, account=account,
            entry_plaza=entry, status=TripStatus.ACTIVE,
        )

        client = APIClient()
        client.force_authenticate(user=owner)

        def get(path):
            response = client.get(path)
            if response.status_code != 200:
                raise RuntimeError(f'{path} returned {response.status_code}')
            return response.json()

        return {
            'auth_me': get('/api/v1/auth/me/'),
            'vehicles_my': get('/api/v1/vehicles/my/'),
            'vehicle_detail': get(f'/api/v1/vehicles/{vehicle.id}/'),
            'accounts_summary': get('/api/v1/accounts/my/summary/'),
            'account_detail': get(f'/api/v1/accounts/vehicle/{vehicle.id}/'),
            'transactions': get(f'/api/v1/accounts/{account.id}/transactions/'),
            'trips': get(f'/api/v1/tolls/trips/{vehicle.id}/'),
            'trips_active': get(f'/api/v1/tolls/trips/{bare.id}/'),
            # The account-wide union the Activity tab reads. Captured separately from
            # the per-vehicle pages because it is the one that carries plate_number for
            # rows belonging to DIFFERENT vehicles — the field the trip list renders to
            # tell two of a holder's cars apart.
            'trips_my': get('/api/v1/tolls/trips/my/'),
            'trips_my_active': get('/api/v1/tolls/trips/my/?status=active'),
            'plazas': get('/api/v1/tolls/plazas/'),
            'fares': get('/api/v1/tolls/rates/'),
            'vehicle_categories': get('/api/v1/tolls/vehicle-categories/'),
            'topup_history': get(f'/api/v1/payments/history/{account.id}/'),
        }


class _Rollback(Exception):
    """Sentinel that unwinds the atomic block after the fixtures are written."""
