# Generated by Django 6.0.4 on 2026-08-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_password_set_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('password_setup', 'Password setup'), ('password_reset', 'Password reset')], default='password_setup', max_length=32),
        ),
    ]
