import 'dart:convert';
import 'dart:io';

import 'package:decimal/decimal.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mtag_user_app/core/models/account.dart';
import 'package:mtag_user_app/core/models/enums.dart';
import 'package:mtag_user_app/core/models/tag.dart';
import 'package:mtag_user_app/core/models/toll.dart';
import 'package:mtag_user_app/core/models/topup.dart';
import 'package:mtag_user_app/core/models/trip.dart';
import 'package:mtag_user_app/core/models/user.dart';
import 'package:mtag_user_app/core/models/vehicle.dart';
import 'package:mtag_user_app/core/network/api_envelope.dart';
import 'package:mtag_user_app/core/utils/money.dart';

/// Contract tests against **real** backend responses.
///
/// The fixtures in `test/fixtures/` are not hand-written. They are generated by driving the
/// actual Django views through DRF against a real database:
///
/// ```sh
/// cd ../mtag_backend
/// python manage.py dump_api_fixtures
/// ```
///
/// That distinction is the whole value. A hand-written fixture only proves the parser
/// matches the fixture; a captured one proves the parser matches the SERVER. If a
/// serializer gains, loses or renames a field, regenerating these makes this file fail —
/// which is exactly when a hand-written parser would otherwise start silently returning
/// nulls.
///
/// The fixtures deliberately include the awkward states: a vehicle with no tag, a
/// blocked-level balance, an offline-synced toll, a transaction with a null `source`, an
/// active trip with null exit fields, and asymmetric fares.
void main() {
  dynamic fixture(String name) {
    final file = File('test/fixtures/$name.json');
    expect(
      file.existsSync(),
      isTrue,
      reason:
          'Missing test/fixtures/$name.json — regenerate with '
          '`python manage.py dump_api_fixtures` in ../mtag_backend.',
    );
    return jsonDecode(file.readAsStringSync());
  }

  group('GET /auth/me/', () {
    test('parses into AppUser', () {
      final user = ApiEnvelope.parse<AppUser>(
        fixture('auth_me'),
        (data) => AppUser.fromApi(data as Map<String, dynamic>),
      ).required;

      expect(user.fullName, 'Fixture Holder');
      expect(user.role, UserRole.user);
      expect(user.role.isConsumer, isTrue);
      expect(user.status, UserStatus.active);
      expect(user.cnic, '42101-1234567-1');
      expect(user.createdAt, isNotNull);
    });
  });

  group('GET /vehicles/my/', () {
    late List<MyVehicle> vehicles;

    setUp(() {
      vehicles = ApiEnvelope.parse<List<MyVehicle>>(
        fixture('vehicles_my'),
        (data) => (data as List)
            .whereType<Map<String, dynamic>>()
            .map(MyVehicle.fromApi)
            .toList(),
      ).required;
    });

    test('parses both vehicles, including the one with no tag', () {
      expect(vehicles.length, 2);
      expect(vehicles.where((v) => v.hasTag).length, 1);
      // The tagless vehicle is PRESENT, not dropped — it is the reissue-in-progress case a
      // worried owner opens the app to check.
      expect(vehicles.where((v) => !v.hasTag).length, 1);
    });

    test('money arrives as a string and becomes an exact Decimal', () {
      final rich = vehicles.firstWhere((v) => v.hasTag);
      expect(rich.balance, Decimal.parse('1250.00'));
      expect(rich.balanceLevel, BalanceLevel.ok);
    });

    test('a Rs. 42 balance is classified as BLOCKED, not merely low', () {
      // Below settings.MINIMUM_ACCOUNT_BALANCE, so the barrier will not open. This is the
      // classification the urgent dashboard banner keys on.
      final poor = vehicles.firstWhere((v) => !v.hasTag);
      expect(poor.balance, Decimal.parse('42.00'));
      expect(poor.balanceLevel, BalanceLevel.blocked);
      expect(poor.canEnter, isFalse);
    });

    test('tid and epc are exposed — the JazzCash flow depends on tid', () {
      final tag = vehicles.firstWhere((v) => v.hasTag).tag!;
      expect(tag.tid, isNotNull);
      expect(tag.tid, startsWith('E280117'));
      expect(tag.epc, isNotNull);
      expect(tag.canShowJazzCashInstructions, isTrue);
    });

    test('is_valid is taken from the server, and the tag is usable', () {
      final tag = vehicles.firstWhere((v) => v.hasTag).tag!;
      expect(tag.isValid, isTrue);
      expect(tag.status, TagStatus.active);
      // Expiry is 2099, so no warning.
      expect(tag.isExpiringSoon, isFalse);
    });

    test('the fare class survives as a real VehicleType, not a raw string', () {
      final truck = vehicles.firstWhere((v) => !v.hasTag);
      expect(truck.vehicleType, VehicleType.truck2Axle);
      expect(truck.vehicleType.isPermittedOnExpressway, isTrue);
    });

    test('account_id is present and distinct from the vehicle id concept', () {
      for (final vehicle in vehicles) {
        expect(vehicle.accountId, isNotNull);
      }
    });
  });

  group('GET /accounts/my/summary/', () {
    late AccountSummary summary;

    setUp(() {
      summary = ApiEnvelope.parse<AccountSummary>(
        fixture('accounts_summary'),
        (data) => AccountSummary.fromApi(data as Map<String, dynamic>),
      ).required;
    });

    test('the total is the exact sum of the per-vehicle wallets', () {
      // 1250.00 + 42.00. Not spendable as one figure — the app labels it as a sum.
      expect(summary.totalBalance, Decimal.parse('1292.00'));
      expect(summary.accountCount, 2);
    });

    test('tag_count counts TAGS, not vehicles', () {
      // Two vehicles, one tag. Conflating them would report a tag the user cannot use.
      expect(summary.vehicleCount, 2);
      expect(summary.tagCount, 1);
    });

    test('month-to-date counts only successful toll deductions', () {
      // The fixture has a toll (120), a top-up (1000) and a refund (60) this month. Only
      // the toll counts.
      expect(summary.monthTollTotal, Decimal.parse('120.00'));
      expect(summary.monthTollCount, 1);
    });

    test(
      'recent transactions carry the plate, so a merged feed can label them',
      () {
        expect(summary.recentTransactions, isNotEmpty);
        for (final transaction in summary.recentTransactions) {
          expect(transaction.accountId, isNotNull);
          expect(transaction.plateNumber, isNotNull);
        }
      },
    );

    test('a server-provided summary is not marked partial', () {
      expect(summary.isPartial, isFalse);
    });
  });

  group('GET /accounts/{id}/transactions/', () {
    late List<Transaction> transactions;

    setUp(() {
      transactions = PagedEnvelope.parse<Transaction>(
        fixture('transactions'),
        Transaction.fromApi,
      ).items;
    });

    test('the offline-synced toll is identifiable', () {
      // A booth can run offline and syncs every 30s, so this charge reached the server
      // after the trip. Without `source` the app could not explain a late-appearing toll.
      final toll = transactions.firstWhere(
        (t) => t.type == TransactionType.tollDeduction,
      );
      expect(toll.source, TransactionSource.offlineExitSync);
      expect(toll.wasSyncedFromBooth, isTrue);
      expect(toll.isCredit, isFalse);
      expect(toll.amount, Decimal.parse('120.00'));
    });

    test('a top-up is a credit and carries its source', () {
      final topup = transactions.firstWhere(
        (t) => t.type == TransactionType.topup,
      );
      expect(topup.source, TransactionSource.topupJazzCash);
      expect(topup.isCredit, isTrue);
      expect(topup.wasSyncedFromBooth, isFalse);
    });

    test('a NULL source parses to unknown rather than throwing', () {
      // Several server paths create transactions without setting `source`, so absent is
      // common rather than exceptional.
      final refund = transactions.firstWhere(
        (t) => t.type == TransactionType.refund,
      );
      expect(refund.source, TransactionSource.unknown);
      expect(refund.isCredit, isTrue);
    });

    test('balance_before and balance_after are exact', () {
      final toll = transactions.firstWhere(
        (t) => t.type == TransactionType.tollDeduction,
      );
      expect(toll.balanceBefore, Decimal.parse('1370.00'));
      expect(toll.balanceAfter, Decimal.parse('1250.00'));
      // The arithmetic holds exactly, which is the point of Decimal.
      expect(toll.balanceBefore! - toll.amount, toll.balanceAfter);
    });
  });

  group('GET /tolls/trips/{vehicle_id}/', () {
    test('a completed trip has both plazas, a duration and a fare', () {
      final trips = PagedEnvelope.parse<TollTrip>(
        fixture('trips'),
        TollTrip.fromApi,
      ).items;

      final trip = trips.firstWhere((t) => t.status == TripStatus.completed);
      expect(trip.entryPlazaName, 'Fixture Main Toll Plaza');
      expect(trip.exitPlazaName, 'Fixture Interchange');
      expect(trip.chargeAmount, Decimal.parse('120.00'));
      expect(trip.durationMinutes, isNotNull);
      expect(trip.isLive, isFalse);
    });

    test('an ACTIVE trip has null exit fields, and that is valid data', () {
      final trips = PagedEnvelope.parse<TollTrip>(
        fixture('trips_active'),
        TollTrip.fromApi,
      ).items;

      final live = trips.firstWhere((t) => t.status == TripStatus.active);
      expect(live.isLive, isTrue);
      // Null because the vehicle is still on the expressway — not missing data, and the UI
      // renders a distinct live card rather than dashes where a fare belongs.
      expect(live.exitPlazaName, isNull);
      expect(live.exitTime, isNull);
      expect(live.chargeAmount, isNull);
      expect(live.durationMinutes, isNull);
      expect(live.elapsedSoFar, isNotNull);
    });
  });

  group('GET /tolls/trips/my/', () {
    test('returns trips from MORE THAN ONE vehicle in a single ordered page', () {
      // The reason this endpoint exists. The per-vehicle route can only ever answer for
      // one plate, so an account-wide list had to fan out client-side and merge N
      // paginated streams — and page 1 of two vehicles is not the first page of their
      // union, so the merged order was wrong wherever it mattered.
      final envelope = PagedEnvelope.parse<TollTrip>(
        fixture('trips_my'),
        TollTrip.fromApi,
      );

      final plates = envelope.items.map((t) => t.plateNumber).toSet();
      expect(
        plates.length,
        greaterThan(1),
        reason: 'the fixture must cover two vehicles or it proves nothing',
      );

      // plate_number is what the row renders to tell one of the holder's cars from
      // another. Blank would leave the list ambiguous rather than merely plain.
      for (final trip in envelope.items) {
        expect(trip.plateNumber, isNotEmpty);
      }
    });

    test('newest first, so appending page 2 cannot reorder page 1', () {
      final items = PagedEnvelope.parse<TollTrip>(
        fixture('trips_my'),
        TollTrip.fromApi,
      ).items;

      final times = items
          .map((t) => t.entryTime)
          .whereType<DateTime>()
          .toList(growable: false);
      expect(times.length, items.length, reason: 'every trip needs an entry_time');

      for (var i = 1; i < times.length; i++) {
        expect(
          times[i].isAfter(times[i - 1]),
          isFalse,
          reason: 'row $i is newer than the row above it',
        );
      }
    });

    test('pagination meta parses, so the list knows whether to keep loading', () {
      final meta = PagedEnvelope.parse<TollTrip>(
        fixture('trips_my'),
        TollTrip.fromApi,
      ).meta;

      expect(meta.count, greaterThan(0));
      expect(meta.currentPage, 1);
      // The fixture fits on one page, so hasMore must be false — a true here would make
      // the list request a page 2 that does not exist on every scroll to the bottom.
      expect(meta.hasMore, isFalse);
    });

    test('?status=active narrows to open trips only', () {
      final items = PagedEnvelope.parse<TollTrip>(
        fixture('trips_my_active'),
        TollTrip.fromApi,
      ).items;

      expect(items, isNotEmpty);
      expect(items.every((t) => t.isLive), isTrue);
      // Server-side filtering, so the count reflects the whole history rather than
      // whatever happened to land on the first page.
      for (final trip in items) {
        expect(trip.exitTime, isNull);
        expect(trip.chargeAmount, isNull);
      }
    });
  });

  group('GET /tolls/plazas/ and /tolls/rates/', () {
    test('plaza_id, row id and display_id stay distinct', () {
      final plazas = ApiEnvelope.parse<List<Plaza>>(
        fixture('plazas'),
        (data) => (data as List)
            .whereType<Map<String, dynamic>>()
            .map(Plaza.fromApi)
            .toList(),
      ).required;

      final main = plazas.firstWhere((p) => p.plazaId == 9001);
      expect(main.name, 'Fixture Main Toll Plaza');
      // A 4-digit fixture plaza_id is not padded, which is correct — padding is to 3.
      expect(main.displayId, '9001');
      expect(main.latitude, closeTo(24.85, 0.001));
    });

    test('the fare matrix joins on plaza ROW id and category_code', () {
      final plazas = ApiEnvelope.parse<List<Plaza>>(
        fixture('plazas'),
        (data) => (data as List)
            .whereType<Map<String, dynamic>>()
            .map(Plaza.fromApi)
            .toList(),
      ).required;
      final fares = ApiEnvelope.parse<List<Fare>>(
        fixture('fares'),
        (data) => (data as List)
            .whereType<Map<String, dynamic>>()
            .map(Fare.fromApi)
            .toList(),
      ).required;
      final matrix = FareMatrix(fares);

      final from = plazas.firstWhere((p) => p.plazaId == 9001);
      final to = plazas.firstWhere((p) => p.plazaId == 9101);

      final car = matrix.lookup(
        fromPlazaId: from.id,
        toPlazaId: to.id,
        vehicleType: VehicleType.car,
      );
      expect(car?.fare, Decimal.parse('100.00'));

      final truck = matrix.lookup(
        fromPlazaId: from.id,
        toPlazaId: to.id,
        vehicleType: VehicleType.truck2Axle,
      );
      expect(truck?.fare, Decimal.parse('350.00'));
    });

    test('fares are directional in the real data, not just in theory', () {
      final plazas = ApiEnvelope.parse<List<Plaza>>(
        fixture('plazas'),
        (data) => (data as List)
            .whereType<Map<String, dynamic>>()
            .map(Plaza.fromApi)
            .toList(),
      ).required;
      final matrix = FareMatrix(
        ApiEnvelope.parse<List<Fare>>(
          fixture('fares'),
          (data) => (data as List)
              .whereType<Map<String, dynamic>>()
              .map(Fare.fromApi)
              .toList(),
        ).required,
      );

      final a = plazas.firstWhere((p) => p.plazaId == 9001);
      final b = plazas.firstWhere((p) => p.plazaId == 9101);

      final forward = matrix.lookup(
        fromPlazaId: a.id,
        toPlazaId: b.id,
        vehicleType: VehicleType.car,
      );
      final reverse = matrix.lookup(
        fromPlazaId: b.id,
        toPlazaId: a.id,
        vehicleType: VehicleType.car,
      );

      expect(forward?.fare, Decimal.parse('100.00'));
      expect(reverse?.fare, Decimal.parse('120.00'));
    });

    test(
      'category is the integer category_index, and code maps to VehicleType',
      () {
        final categories = ApiEnvelope.parse<List<VehicleCategory>>(
          fixture('vehicle_categories'),
          (data) => (data as List)
              .whereType<Map<String, dynamic>>()
              .map(VehicleCategory.fromApi)
              .toList(),
        ).required;

        final car = categories.firstWhere((c) => c.code == 'car');
        expect(car.categoryIndex, 901);
        expect(car.vehicleType, VehicleType.car);
        // The row id and the business key are different numbers.
        expect(car.id, isNot(car.categoryIndex));
      },
    );
  });

  group('GET /payments/history/{account_id}/', () {
    test('the pending top-up parses and is not settled', () {
      final topups = ApiEnvelope.parse<List<TopupRequest>>(
        fixture('topup_history'),
        (data) => (data as List)
            .whereType<Map<String, dynamic>>()
            .map(TopupRequest.fromApi)
            .toList(),
      ).required;

      expect(topups.length, 1);
      expect(topups.first.amount, Decimal.parse('500.00'));
      expect(topups.first.status, TopupStatus.pending);
      expect(topups.first.status.isSettled, isFalse);
      expect(topups.first.completedAt, isNull);
    });
  });

  group('GET /vehicles/{id}/', () {
    test('carries the owner fields that /vehicles/my/ does not', () {
      final vehicle = ApiEnvelope.parse<VehicleDetail>(
        fixture('vehicle_detail'),
        (data) => VehicleDetail.fromApi(data as Map<String, dynamic>),
      ).required;

      expect(vehicle.ownerName, 'Fixture Holder');
      expect(vehicle.ownerPhone, isNotNull);
      expect(vehicle.ownerId, isNotNull);
      expect(vehicle.tag?.tid, isNotNull);
    });
  });

  group('money round-trips through the real wire format', () {
    test('every balance in every fixture re-serialises identically', () {
      // Proves the Decimal pipeline is lossless against real server output, which is the
      // one thing a `double` would silently break.
      for (final name in ['vehicles_my', 'accounts_summary', 'transactions']) {
        final raw = jsonEncode(fixture(name));
        for (final match in RegExp(r'"(\d+\.\d{2})"').allMatches(raw)) {
          final value = match.group(1)!;
          expect(
            Money.toApiString(Money.tryParse(value)!),
            value,
            reason: '$value did not survive a round trip (in $name)',
          );
        }
      }
    });
  });
}
